import IIS_Modul_ucheta_sroka_dejjstviya_dogovoraКлиентEController from '../i-i-s-modul-ucheta-sroka-dejjstviya-dogovora-клиент-e';

var IIS_Modul_ucheta_sroka_dejjstviya_dogovoraКлиентENewController = IIS_Modul_ucheta_sroka_dejjstviya_dogovoraКлиентEController;
export default IIS_Modul_ucheta_sroka_dejjstviya_dogovoraКлиентENewController;
